/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jetbrains.demo;

// Added a comment to this class
// Add another comment to see updates in TC
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
