/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jetbrains.demo;

// Add a comment to the App class
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
